# Generated by Django 6.0.2 on 2026-05-09 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_guest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.TextField(help_text='Use a URL or a data URI for demo room images.'),
        ),
    ]
