# Generated by Django 6.0.2 on 2026-10-03 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_room_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Reserved', 'Reserved'), ('Checked-in', 'Checked-in'), ('Checked-out', 'Checked-out'), ('Cancelled', 'Cancelled')], default='Reserved', max_length=20),
        ),
    ]
